kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/q-svc-prisma
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: q-svc-prisma
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]q-svc-prisma.<guid>.<region>.aksapp.io
      - $(spacePrefix)q-svc-prisma$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true