projects:
  app:
    schemaPath: ../logic/src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: ../logic/src/generated/prisma.graphql
    extensions:
      prisma: ./prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: ../logic/src/generated/prisma.ts
